// Generated by tools/gen_js_defaults.py from flashcard_viewer/config.py — do not edit by hand.
export const APP_VERSION = "1.2.3";
export const DEFAULTS = {
  "appearance": {
    "mode": "system",
    "theme": "baseline",
    "seed": "#6750A4",
    "variant": "tonalSpot",
    "contrast": "standard",
    "amoled": false,
    "glass": false,
    "glassBlur": 24,
    "glassOpacity": 0.62,
    "catppuccinDark": "mocha",
    "catppuccinAccent": "mauve",
    "gruvboxContrast": "medium",
    "font": "Roboto Flex",
    "headingFont": "",
    "monoFont": "Maple Mono",
    "fontScale": 1.0,
    "uiScale": 1.0,
    "corner": 1.0,
    "iconStyle": "rounded",
    "iconFill": false,
    "iconWeight": 400,
    "density": "comfortable"
  },
  "motion": {
    "enabled": true,
    "speed": 1.0,
    "reduce": false,
    "rippleEffects": true
  },
  "decks": {
    "applyAppFont": false,
    "applyTheme": "off",
    "zoom": 1.0,
    "autoReload": true,
    "rememberPosition": true
  },
  "library": {
    "folders": [],
    "mainFolder": "",
    "recursive": true,
    "sort": "name",
    "favouritesFirst": true,
    "showCardCount": true,
    "view": "list"
  },
  "network": {
    "mode": "offline-first"
  },
  "quiz": {
    "questions": 10,
    "types": {
      "typed": true,
      "mc": true,
      "tf": true
    },
    "threshold": 0.75,
    "stripAccents": true,
    "shuffle": true,
    "timer": 0,
    "sounds": true,
    "showExplanations": true,
    "promptOnFinish": true,
    "promptAfterMinutes": 0,
    "weakFirst": true,
    "autoAdvance": false
  },
  "window": {
    "customTitlebar": true,
    "width": 1280,
    "height": 820,
    "maximized": false,
    "sidebarWidth": 300,
    "sidebarCollapsed": false
  },
  "shortcuts": {
    "search": "Ctrl+K",
    "fullscreen": "F11",
    "focusMode": "Ctrl+Shift+F",
    "quiz": "Ctrl+Q",
    "nextDeck": "Ctrl+ArrowDown",
    "prevDeck": "Ctrl+ArrowUp",
    "zoomIn": "Ctrl+=",
    "zoomOut": "Ctrl+-",
    "zoomReset": "Ctrl+0",
    "reload": "Ctrl+R",
    "favourite": "Ctrl+D",
    "library": "Ctrl+1",
    "quizPage": "Ctrl+2",
    "stats": "Ctrl+3",
    "settings": "Ctrl+,",
    "toggleSidebar": "Ctrl+B",
    "openFile": "Ctrl+O",
    "cheatsheet": "Ctrl+/"
  },
  "general": {
    "startPage": "library",
    "lastDeck": "",
    "confirmDelete": true,
    "singleInstance": true,
    "checkUpdates": true,
    "lastUpdateCheck": 0,
    "skippedVersion": ""
  }
};
export const DEFAULT_LIBRARY = {
  "favourites": [],
  "renames": {},
  "recent": [],
  "external": [],
  "positions": {}
};
