// Builds the offline vendor assets in flashcard_viewer/ui/vendor.
// Usage: cd tools/vendor-build && npm install && node build.mjs
import { build } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';

const here = path.dirname(new URL(import.meta.url).pathname);
const nm = path.join(here, 'node_modules');
const out = path.resolve(here, '../../flashcard_viewer/ui/vendor');

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(path.join(out, 'fonts'), { recursive: true });

const copy = (src, dst) => {
  fs.mkdirSync(path.dirname(path.join(out, dst)), { recursive: true });
  fs.copyFileSync(path.join(nm, src), path.join(out, dst));
};

// 1. Material Web components + Material color utilities, as one ES module.
await build({
  stdin: {
    contents: `import '@material/web/all.js';\nexport * from '@material/material-color-utilities';\n`,
    resolveDir: here,
    loader: 'js',
  },
  bundle: true,
  format: 'esm',
  minify: true,
  legalComments: 'none',
  target: 'chrome120',
  outfile: path.join(out, 'material.js'),
});

// 2. Material Symbols (variable fonts: FILL, wght, GRAD, opsz axes).
for (const style of ['outlined', 'rounded', 'sharp']) {
  copy(`material-symbols/material-symbols-${style}.woff2`, `fonts/material-symbols-${style}.woff2`);
}

// 3. Text fonts. Keep latin + latin-ext subsets of the weights the UI uses.
const SUBSETS = ['latin', 'latin-ext'];
let css = '/* Generated by tools/vendor-build/build.mjs */\n';
const fontsource = (pkg, weights, styles = ['normal']) => {
  for (const w of weights) {
    for (const st of styles) {
      const file = path.join(nm, pkg, st === 'normal' ? `${w}.css` : `${w}-${st}.css`);
      if (!fs.existsSync(file)) continue;
      const blocks = fs.readFileSync(file, 'utf8').split('@font-face').slice(1);
      for (const b of blocks) {
        const m = b.match(/url\(\.\/files\/([^)]+?\.woff2)\)/);
        if (!m) continue;
        const name = m[1];
        if (!SUBSETS.some((s) => name.includes(`-${s}-${w}-`))) continue;
        copy(`${pkg}/files/${name}`, `fonts/${name}`);
        const body = b
          .replace(/src:[^;]+;/, `src: url(./fonts/${name}) format('woff2');`)
          .trim();
        css += `@font-face ${body}\n`;
      }
    }
  }
};
fontsource('@fontsource/roboto', [400, 500, 700], ['normal', 'italic']);
fontsource('@fontsource/inter', [400, 500, 600, 700]);
fontsource('@fontsource/outfit', [400, 500, 600, 700]);
fontsource('@fontsource/lexend', [400, 500, 600, 700]);
fontsource('@fontsource/atkinson-hyperlegible', [400, 700], ['normal', 'italic']);
fontsource('@fontsource/comic-relief', [400, 700]);
fontsource('@fontsource/maple-mono', [400, 500, 700], ['normal', 'italic']);

// Roboto Flex (variable).
{
  const pkg = '@fontsource-variable/roboto-flex';
  const blocks = fs.readFileSync(path.join(nm, pkg, 'index.css'), 'utf8').split('@font-face').slice(1);
  for (const b of blocks) {
    const m = b.match(/url\(\.\/files\/([^)]+?\.woff2)\)/);
    if (!m || !SUBSETS.some((s) => m[1].includes(`-${s}-`))) continue;
    copy(`${pkg}/files/${m[1]}`, `fonts/${m[1]}`);
    css += `@font-face ${b.replace(/src:[^;]+;/, `src: url(./fonts/${m[1]}) format('woff2-variations');`).trim()}\n`;
  }
}

// Comic Mono (not on Google Fonts; MIT licensed, from dtinth/comic-mono-font).
copy('comic-mono/ComicMono.ttf', 'fonts/ComicMono.ttf');
copy('comic-mono/ComicMono-Bold.ttf', 'fonts/ComicMono-Bold.ttf');
css += `@font-face { font-family: 'Comic Mono'; font-weight: 400; font-display: swap; src: url(./fonts/ComicMono.ttf) format('truetype'); }\n`;
css += `@font-face { font-family: 'Comic Mono'; font-weight: 700; font-display: swap; src: url(./fonts/ComicMono-Bold.ttf) format('truetype'); }\n`;

for (const style of ['outlined', 'rounded', 'sharp']) {
  const family = `Material Symbols ${style[0].toUpperCase()}${style.slice(1)}`;
  css += `@font-face { font-family: '${family}'; font-style: normal; font-weight: 100 700; font-display: block; src: url(./fonts/material-symbols-${style}.woff2) format('woff2'); }\n`;
}
fs.writeFileSync(path.join(out, 'fonts.css'), css);

// 4. Runtime for React / JSX artifacts (artifact-style React components).
copy('react/umd/react.production.min.js', 'react/react.production.min.js');
copy('react-dom/umd/react-dom.production.min.js', 'react/react-dom.production.min.js');
copy('@babel/standalone/babel.min.js', 'react/babel.min.js');
copy('@tailwindcss/browser/dist/index.global.js', 'react/tailwind.js');
// lucide UMD expects a global named `react`.
await build({
  entryPoints: [path.join(nm, 'lucide-react/dist/umd/lucide-react.js')],
  minify: true,
  legalComments: 'none',
  outfile: path.join(out, 'react/lucide-react.min.js'),
  banner: { js: 'var react = window.React;' },
});

// 5. KaTeX, for maths in decks made with the deck editor (woff2 fonts only).
copy('katex/dist/katex.min.js', 'katex/katex.min.js');
fs.writeFileSync(path.join(out, 'katex/katex.min.css'), fs.readFileSync(path.join(nm, 'katex/dist/katex.min.css'), 'utf8')
  .replace(/,url\([^)]+\.woff\) format\("woff"\),url\([^)]+\.ttf\) format\("truetype"\)/g, ''));
for (const f of fs.readdirSync(path.join(nm, 'katex/dist/fonts'))) {
  if (f.endsWith('.woff2')) copy(`katex/dist/fonts/${f}`, `katex/fonts/${f}`);
}

// Licenses.
const lic = [
  ['@material/web', 'LICENSE'],
  ['@material/material-color-utilities', 'LICENSE'],
  ['material-symbols', 'LICENSE'],
  ['comic-mono', 'LICENSE'],
  ['react', 'LICENSE'],
  ['lucide-react', 'LICENSE'],
  ['@tailwindcss/browser', 'LICENSE'],
  ['@fontsource/maple-mono', 'LICENSE'],
  ['@fontsource/inter', 'LICENSE'],
  ['katex', 'LICENSE'],
];
let notices = 'Third-party assets bundled for offline use. Fonts from Google Fonts / Fontsource are licensed under the SIL Open Font License 1.1.\n\n';
for (const [pkg, f] of lic) {
  const p = path.join(nm, pkg, f);
  if (fs.existsSync(p)) notices += `==== ${pkg} ====\n${fs.readFileSync(p, 'utf8')}\n\n`;
  else notices += `==== ${pkg} ==== (see package)\n\n`;
}
fs.writeFileSync(path.join(out, 'THIRD_PARTY_NOTICES.txt'), notices);
console.log('vendor built in', out);
