"""Write flashcard_viewer/ui/js/core/defaults.js from the Python settings defaults.

    python3 tools/gen_js_defaults.py
(tests/test_js_defaults.py fails if the generated file is out of date.)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from flashcard_viewer import __version__  # noqa: E402
from flashcard_viewer.config import DEFAULT_LIBRARY, DEFAULTS  # noqa: E402

OUT = ROOT / "flashcard_viewer" / "ui" / "js" / "core" / "defaults.js"


def render() -> str:
    return (
        "// Generated by tools/gen_js_defaults.py from flashcard_viewer/config.py — do not edit by hand.\n"
        f"export const APP_VERSION = {json.dumps(__version__)};\n"
        f"export const DEFAULTS = {json.dumps(DEFAULTS, indent=2, ensure_ascii=False)};\n"
        f"export const DEFAULT_LIBRARY = {json.dumps(DEFAULT_LIBRARY, indent=2)};\n"
    )


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print("wrote", OUT)
